- name: update apt cache
  apt: update_cache=yes
  become: true
  tags:
    - rbenv

- name: install build depends
  apt: pkg={{ item }} state=present install_recommends=no
  with_items:
    - autoconf
    - bison
    - build-essential
    - git
    - libssl-dev
    - libyaml-dev
    - libreadline6-dev
    - zlib1g-dev
    - libncurses5-dev
    - libffi-dev
    - libgdbm3
    - libgdbm-dev
  become: true
  tags:
    - rbenv

