---
- include: apt_build_depends.yml
  when: ansible_pkg_mgr == 'apt'
- include: yum_build_depends.yml
  when: ansible_pkg_mgr == 'yum'
- include: dnf_build_depends.yml
  when: ansible_pkg_mgr == 'dnf'

- include: for_me.yml
  when: rbenv_users is not defined
  static: no
- include: for_others.yml
  when: rbenv_users is defined
  static: no
