---
- name: install build depends
  yum: name={{ item }} state=present
  with_items:
    - make
    - gcc
    - bzip2
    - openssl-devel
    - libyaml-devel
    - libffi-devel
    - readline-devel
    - zlib-devel
    - gdbm-devel
    - ncurses-devel
    - git
  become: true
  tags:
    - rbenv

